volumes:
  postgres-data:
services:
  frontend:
    build:
      context: ./benchmarkFrontend
      dockerfile: Dockerfile.frontend
    restart: always
    depends_on:
      - api
    ports:
      - "3001:3001"
  api:
    build:
      context: ./benchmarkBackend
      dockerfile: Dockerfile.api
    restart: always
    environment:
      - DOCKER_DATABASE_URL=database
    ports:
      - "8080:3000"
    depends_on:
      - database
  database:
    image: postgres:15.2
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      #add initial data to the database, this file isnt uploaded so use schema only instead
      #- ./db_init_data.sql:/docker-entrypoint-initdb.d/init.sql
      - ./benchmarkBackend/db/dbschema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=admin
